### ISSUE TITLE
mypy says `Library stubs not installed for "yaml"`

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/digipipe#72]
With the pre-commit introduced in #64 this message persists:
```
digipipe/scripts/config.py:8: error: Library stubs not installed for "yaml"  [import]
digipipe/scripts/config.py:8: note: Hint: "python3 -m pip install types-PyYAML"
digipipe/scripts/config.py:8: note: (or run "mypy --install-types" to install all missing stub packages)
digipipe/scripts/config.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Both suggested solutions (`pip install types-PyYAML` and `mypy --install-types`) fixed the error. Do you wanna add it to the package list? Or shall we suppress it like @henhuy did as described in https://github.com/rl-institut-private/digipipe/pull/64#issuecomment-1512613173?
